### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by jinjoo-lab** [HongDam-org/TWTW#91]
![Untitled](https://github.com/HongDam-org/TWTW/assets/84346055/a952ade3-1327-4e60-8d8d-401376f4b7c8)
![Untitled 1](https://github.com/HongDam-org/TWTW/assets/84346055/453c8a82-ac64-46c8-83f2-d2f96e174750)
![Untitled 2](https://github.com/HongDam-org/TWTW/assets/84346055/ee7192b0-4688-4642-a78a-577d1c26c97a)
![Untitled 3](https://github.com/HongDam-org/TWTW/assets/84346055/1f903d0f-536f-456a-b3c1-8f7a17ebc1c2)
![Untitled 4](https://github.com/HongDam-org/TWTW/assets/84346055/be91bed4-960e-43e6-a5aa-aed2a0e816c7)
![Untitled 5](https://github.com/HongDam-org/TWTW/assets/84346055/103e5556-2ae5-4e2e-8ede-b21ed901f5c3)
![Untitled 6](https://github.com/HongDam-org/TWTW/assets/84346055/c0964a24-16fd-4bcf-81f1-dbec60052008)
![Untitled 7](https://github.com/HongDam-org/TWTW/assets/84346055/d80ecf5d-eaa5-4303-890c-ce64c32b9f6f)
![Untitled 8](https://github.com/HongDam-org/TWTW/assets/84346055/143e6400-33b0-4f3a-8477-2ace129ff807)
![%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2024-03-13_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_5 20 43](https://github.com/HongDam-org/TWTW/assets/84346055/49758773-3be9-4645-95df-bd7f71dacadc)
![%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2024-03-13_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_5 34 24](https://github.com/HongDam-org/TWTW/assets/84346055/acc218ad-4aef-44e2-b380-5f35139d086c)
![%E1%84%89%E1%85%B3%E1%84%8F%E1%85%B3%E1%84%85%E1%85%B5%E1%86%AB%E1%84%89%E1%85%A3%E1%86%BA_2024-03-13_%E1%84%8B%E1%85%A9%E1%84%92%E1%85%AE_5 36 44](https://github.com/HongDam-org/TWTW/assets/84346055/cfef0975-bdf5-40b4-b61d-42eb8d155564)

**Comment by ohksj77** [comment]
이미지를 한 번 링크로 만들었다면 이슈로 올리지 않아도 링크는 유효합니다.
